#!/data/data/com.termux/files/usr/bin/bash


# Auto Install Tools

# Username: MrXerxesID

# Hostname: Projoki

# FB: Risa Permana

# E-mail: projoki.tv@gmail.com

# Telp/Fax: +6283120027137

# Website: https://projoki.blogspot.com

# Channel: Projoki. TV

# Like Comment And Subscribe


# Bersihkan Layar

clear


#This colour

blue='\e[0;34'

cyan='\e[0;36m'

green='\e[0;34m'

okegreen='\033[92m'

lightgreen='\e[1;32m'

white='\e[1;37m'

red='\e[1;31m'

yellow='\e[1;33m'


###################################################

# CTRL C

###################################################

trap ctrl_c INT

ctrl_c() {

clear

echo -e $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "

sleep 1

echo ""

echo -e $yellow"[#]> Thank You For Using My Tools ... "

sleep 1

echo ""

echo -e $white"[#]> Im Here ... "

read enter

exit

}


# Isi oc :*

echo ""

echo -e $white" ***********************************************"

echo -e $cyan" Toolkit For$red Lazy People"

echo -e $cyan" Autor Code by$red MrXerXesID"

echo -e $cyan" Follow Me On Github:$red @Projoki"

echo -e $cyan" My Site:$red https://projoki.blogspot.com"

echo -e $cyan" Contact Me In:$red projoki.tv@gmail.com"                 

echo -e $cyan" Made $red 17-06-2017"                                      

echo -e $cyan" Team: $red INA BLACK HHA"                                        


echo -e $white" ***********************************************"


echo ""

echo -e $yellow" 01) OSIF"

echo -e $yellow" 02) Facebook"

echo -e $yellow" 03) SQLMap"

echo -e $yellow" 04) Dirbuster"

echo -e $yellow" 05) D-Tect"

echo -e $yellow" 06) Kali Nethunter"

echo -e $yellow" 7) Hydra "

echo -e $yellow" 08) Red Hawk"

echo -e $yellow" 09) WFDroid"

echo -e $yellow" 10) viSQL "

echo -e $red" 11) Exit "

echo -e $white""

read -p "[Projoki@Tools]> " act;


if [ $act = 1 ] || [ $act = 01 ]

then

clear

echo -e $red" Installing OSIF "

sleep 1

apt update && apt upgrade

apt install php

apt install git

git clonehttps://github.com/projoki/OSIF-Projoki

cd ~/

echo -e $red" T E R I N S T A L L "

fi
if [ $act = 2 ] || [ $act = 02 ]

then

clear

echo -e $red" Installing Hunner "

sleep 1

apt-get update && apt-get upgrade

apt install python

apt install git

git clone https://github.com/Senitopeng/fbbrute

cd ~/

echo -e $red" T E R I N S T A L L "

fi

if [ $act = 03 ] || [ $act = 03 ]

then

clear

echo -e $red" Installing SQLMap "

sleep 1

apt update && apt upgrade

apt install python2

git clone https://github.com/sqlmapproject/sqlmap.git

cd ~/

echo -e $red" T E R I N S T A L L "

fi

if [ $act = 4 ] || [ $act = 04 ]

then

clear

echo -e $red" Installing Dirbuster "

sleep 1

apt-get update

apt-get install python

apt-get install git

git clone https://github.com/maurosoria/dirsearch.git

cd ~/

echo -e $red" T E R I N S T A L L "

fi

if [ $act = 5 ] || [ $act = 05 ]

then

clear

echo -e $red" Installing D-Tect "

sleep 1

apt-get update && apt-get upgrade

apt-get install git

apt-get install python2

git clone https://github.com/shawarkhanethicalhacker/D-TECT

cd ~/

echo -e $red" T E R I N S T A L L "

fi

if [ $act = 6 ] || [ $act = 06 ]

then

clear

echo -e $red" Installing Kali Nethunter "

sleep 1

apt update && apt upgrade

apt install git

git clone https://github.com/Hax4us/Nethunter-In-Termux.git

cd ~/Nethunter-In-Termux

chmod 777 kalinethunter

sh kalinethunter

cd ~/

echo -e $red" T E R I N S T A L L "

fi

if [ $act = 7 ] || [ $act = 07 ]

then

clear

echo -e $red" Installing Hydra "

sleep 1

apt update && apt install -y wget

apt install hydra

wget http://scrapmaker.com/download/data/wordlists/dictionaries/rockyou.txt

cd ~/

echo -e $red" T E R I N S T A L L "

fi


if [ $act = 8 ] || [ $act = 08 ]

then

clear

echo -e $red" Installing Red Hawk "

sleep 1

apt update && apt upgrade

apt install php

apt install git

git clone https://github.com/Tuhinshubhra/RED_HAWK

echo -e $red" T E R I N S T A L L "

fi

if [ $act = 9 ] || [ $act = 09 ]

then

clear

echo -e $red" Installing WFDroid "

sleep 1

apt update && apt upgrade

apt install wget

mkdir wfdroid

cd ~/wfdroid

wget https://raw.githubusercontent.com/bytezcrew/wfdroid-termux/master/wfdinstall

chmod 777 wfdinstall

sh wfdinstall

cd ~/

echo -e $red" T E R I N S T A L L "

fi

if [ $act = 10 ] || [ $act = 10 ]

then

clear

echo -e $red" Installing viSQL "

sleep 1

apt update && apt upgrade

pkg install git

pkg install python2

git clone https://github.com/blackvkng/viSQL.git

cd ~/viSQL

chmod 777 viSQL.py

cd ~/

echo -e $red" T E R I N S T A L L "

fi

if [ $act = 11 ] || [ $act = 11 ]

then

echo " Ko Udahan Sih     "

sleep 1

echo " Lagi Sibuk Ya?      "

sleep 1

echo " Yaudah Kalo Gitu     "

sleep 1

echo " Hati-hati Dijalan     "

sleep 1

echo " Sampai Ketemu Lagi      "

sleep 1

echo " Byee Byee :*       "

sleep 1

exit

fi

